import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className='font-bold text-center m-4 text-2xl'>SuperHero Identity Manager</h1>

        <div className='mt-10'>
          <div className='rounded-lg p-4 border-2 shadow-md max-w-sm m-4'>
            <h1 className='font-bold mt-4 text-2xl'>SuperHero Identity Manager</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptate, quisquam.
            </p>
            <button className='bg-blue-500 hover:bg-blue-700 mt-3 text-white py-2 px-4 rounded-full'>
              BUTTON
            </button>
          </div></div>
      </main>
    </div>
  )
}
